[theme]
primaryColor = "#6366f1"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#181825"
textColor = "#e0e0e0"
font = "sans serif"
base = "dark"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
